base_dir: "<YOUR_TOOL_DIR>"

tools:
  apktool:
    path: "<YOUR_TOOL_DIR>/apktool.bat"
    version_command: "apktool version"
    version: ""

  jadx:
    path: "<YOUR_TOOL_DIR>/jadx/bin/jadx.bat"
    conf: "<YOUR_TOOL_DIR>/jadx/conf/jadx.conf"
    version: ""

  dex2jar:
    path: "<YOUR_TOOL_DIR>/dex2jar/d2j-dex2jar.bat"
    version: ""

  aapt:
    path: "<YOUR_ANDROID_SDK>/build-tools/<VERSION>/aapt.exe"
    version: ""

  apksigner:
    path: "<YOUR_ANDROID_SDK>/build-tools/<VERSION>/apksigner.bat"
    version: ""

python_tools:
  androguard:
    package: "androguard"
    version: "3.4.0"

  quark_engine:
    package: "quark-engine"
    version: "24.4.1"

  mobsf:
    package: "mobsf"
    api_url: "http://localhost:8000"
    api_key: ""
